theme: jekyll-theme-time-machine
title: WCCI2022 IJCNN-SS-2
description: "Evolving Machine Learning and Deep Learning Models for Computer Vision"
top_image: https//wcci2022.org/wp-content/uploads/2020/07/WCCI2022-padua-logo.png
layout: page
